#!/usr/bin/python

pad_str = '0123456789ABCDEF'

file = open("InputFile/4K.in", "w")
for x in xrange(0, 4*1024/16):
	file.write(pad_str) 
file.close()

file = open("InputFile/256K.in", "w")
for x in xrange(0, 256*1024/16):
	file.write(pad_str)
file.close()

file = open("InputFile/64M.in", "w")
for x in xrange(0, 1024*1024*64/16):
	file.write(pad_str)
file.close()
